### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by BoldorOG** [G-E-N-E-S-I-S/BattlegroundsChams#3]
I am having trouble trying to execute the hack. I opened it in Microsoft Visual and saw all the code but can't find a way to run it. Can anyone help???

**Comment by chienhao10** [comment]
seems like missing a file

**Comment by BoldorOG** [comment]
What missing file ?

**Comment by IIuBKO** [comment]
detours.h

**Comment by YusongWang** [comment]
you maybe missing detours.h

get down this address : 
https://www.microsoft.com/en-us/research/project/detours/?from=http%3A%2F%2Fresearch.microsoft.com%2Fsn%2Fdetours

http://www.cnblogs.com/wangyusong/p/7515870.html

**Comment by G-E-N-E-S-I-S** [comment]
fck off
