### ISSUE TITLE
Some question. Please help.

### ISSUE THREAD

**Issue by VinceXie** [G-E-N-E-S-I-S/BattlegroundsChams#6]
When playing a while , my eye feel not good because the yellow color is too shiny.

There are a few question, hope you can answer. Thank a lot.
 Im a coder but just good at web and Android. Im noob at win and c++. Please help me.

1、how to compile these code? I downloaded from a compiled version.
2、Is it possible to only make leg yellow ? 
3、Is it possible to make other effect? like make bone esp?

Thank a lot.

**Comment by wg2001wg** [comment]
你得去网上下载detour的破解版然后安装拷贝到vs库中，详细步骤你得百度。
至于dx11那个，我也没弄明白，估计也得下载破解版才能用。
编译成功之后只是有个dll，至于怎么使用你还得额外写程序。
特别是如何绕过battleye那个程序也是必须的

**Comment by 13321991990** [comment]
@wg2001wg @G-E-N-E-S-I-S 可否向我分享一个过battleye的方法

**Comment by 13321991990** [comment]
@wg2001wg @G-E-N-E-S-I-S 可否分享给我一个过battleye的方法。。。

**Comment by Makraov** [comment]
@wg2001wg 
ch-han:这个文件我看他的代码就有问题 我看了一下早期代码是可以编译的但是东搞西搞编译出来91K 和论坛的43K完全不符合
然后更新之后的代码在ccheat里面重定义了几个hooks的函数??exc me?没用过微软的hook和d3d，代码只能一知半解。现版本代码确定没任何问题吗？

**Comment by G-E-N-E-S-I-S** [comment]
ching cong ding dong ling ling
